### PR TITLE
spelling correction

### PR DESCRIPTION
**Pull request by IvanKuchin**

### CODE REVIEW

**Review by Happyigr — COMMENTED** [review]
Thank you)

**Comment by IvanKuchin** [comment]
You could accept "Pull request" and all changes that proposed in PR will be applied to your code. Means that you don't need to incorporate all changes over again by yourself. Though if you will .....
Now I see there active conflicts, means that smth already has changed in that part of code and PR can't be accepted straight away. 
Just for you information , PR-s are primary coding collaboration tool.

**Comment by IvanKuchin** [comment]
Check out this tutorial to learn more about git: https://learngitbranching.js.org/

**Comment by Happyigr** [comment]
hm, i will read)


вс, 14 мар. 2021 г. в 01:52, IvanKuchin ***@***.***>:

**Pull request closed without merging**
